common:
  LED: 1
  Return_Delay_Time: 0
  Drive_Mode: 0
  Operating_Mode: 3
  Acceleration_Limit: 0
  Velocity_Limit: 0
  Profile_Velocity: 0
  Profile_Acceleration: 0
joints:
  TC_joint_0:
    ID: 1
    Min_Position_Limit: 1140
    Max_Position_Limit: 2980
  CF_joint_0:
    ID: 3
    Min_Position_Limit: 80
    Max_Position_Limit: 3260
  FT_joint_0:
    ID: 2
    Min_Position_Limit: 0
    Max_Position_Limit: 3350
