common:
  dxl:
    LED: 0
    Return_Delay_Time: 0
    Drive_Mode: 0
    Operating_Mode: 3
    Acceleration_Limit: 0
    Velocity_Limit: 128
    Profile_Velocity: 0
    Profile_Acceleration: 0
    Homing_Offset: 0

#    Min_Position_Limit: 0
#    Max_Position_Limit: 4095
joints:
  # Right

  # Front-right
  - name: coxa_joint_0
    id: 1
    multiplier: 1.00
    offset: 0.00
    dxl:
      Min_Position_Limit: 1210 # Backward
      Max_Position_Limit: 2960 # Forward
  - name: femur_joint_0
    id: 2
    multiplier: 1.00
    offset: -0.684 # (2pi * 39.2) / 360
    dxl:
      LED: 1
      Min_Position_Limit: 860 # Over
      Max_Position_Limit: 3980 # Under
  - name: tibia_joint_0
    id: 3
    multiplier: -1.00
    offset: 1.157 # (2pi * (45 + 21.3)) / 360
    dxl:
      Min_Position_Limit: 760 # Close
      Max_Position_Limit: 4095 # Extended

  - name: coxa_joint_1
    id: 4
    multiplier: 1.00
    offset: 0.00
    dxl:
      Min_Position_Limit: 1210
      Max_Position_Limit: 2960
  - name: femur_joint_1
    id: 5
    multiplier: 1.00
    offset: -0.684
    dxl:
      Min_Position_Limit: 860
      Max_Position_Limit: 3980
  - name: tibia_joint_1
    id: 6
    multiplier: -1.00
    offset: 1.157
    dxl:
      Min_Position_Limit: 760
      Max_Position_Limit: 4095

  - name: coxa_joint_2
    id: 7
    multiplier: 1.00
    offset: 0.00
    dxl:
      Min_Position_Limit: 1210
      Max_Position_Limit: 2960
  - name: femur_joint_2
    id: 8
    multiplier: 1.00
    offset: -0.684
    dxl:
      Min_Position_Limit: 860
      Max_Position_Limit: 3980
  - name: tibia_joint_2
    id: 9
    multiplier: -1.00
    offset: 1.157
    dxl:
      Min_Position_Limit: 760
      Max_Position_Limit: 4095

  - name: coxa_joint_3
    id: 10
    multiplier: 1.00
    offset: 0.00
    dxl:
      Min_Position_Limit: 1140 # Forward
      Max_Position_Limit: 2880 # Backwards
  - name: femur_joint_3
    id: 11
    multiplier: -1.00
    offset: -0.684
    dxl:
      Min_Position_Limit: 80 # Under
      Max_Position_Limit: 3250 # Over
  - name: tibia_joint_3
    id: 12
    multiplier: 1.00
    offset: 1.157
    dxl:
      Min_Position_Limit: 0 # Extended
      Max_Position_Limit: 3350 # Close

  - name: coxa_joint_4
    id: 13
    multiplier: 1.00
    offset: 0.00
    dxl:
      Min_Position_Limit: 1140
      Max_Position_Limit: 2880
  - name: femur_joint_4
    id: 14
    multiplier: -1.00
    offset: -0.684
    dxl:
      Min_Position_Limit: 80
      Max_Position_Limit: 3250
  - name: tibia_joint_4
    id: 15
    multiplier: 1.00
    offset: 1.157
    dxl:
      Min_Position_Limit: 0
      Max_Position_Limit: 3350

  - name: coxa_joint_5
    id: 16
    multiplier: 1.00
    offset: 0.00
    dxl:
      Min_Position_Limit: 1140
      Max_Position_Limit: 2880
  - name: femur_joint_5
    id: 17
    multiplier: -1.00
    offset: -0.684
    dxl:
      Min_Position_Limit: 80
      Max_Position_Limit: 3250
  - name: tibia_joint_5
    id: 18
    multiplier: 1.00
    offset: 1.157
    dxl:
      Min_Position_Limit: 0
      Max_Position_Limit: 3350