common:
  LED: 1
  Return_Delay_Time: 0
  Drive_Mode: 0
  Operating_Mode: 3
  Acceleration_Limit: 0
  Velocity_Limit: 0
  Profile_Velocity: 0
  Profile_Acceleration: 0
joints:
  TC_joint_0:
    ID: 1
    Min_Position_Limit: 1140
    Max_Position_Limit: 2980
  CF_joint_0:
    ID: 3
    Min_Position_Limit: 80
    Max_Position_Limit: 3260
  FT_joint_0:
    ID: 2
    Min_Position_Limit: 0
    Max_Position_Limit: 3350
  TC_joint_1:
    ID: 4
    Min_Position_Limit: 1140
    Max_Position_Limit: 2980
  CF_joint_1:
    ID: 5
    Min_Position_Limit: 80
    Max_Position_Limit: 3260
  FT_joint_1:
    ID: 6
    Min_Position_Limit: 0
    Max_Position_Limit: 3350
  TC_joint_2:
    ID: 7
    Min_Position_Limit: 1140
    Max_Position_Limit: 2980
  CF_joint_2:
    ID: 8
    Min_Position_Limit: 80
    Max_Position_Limit: 3260
  FT_joint_2:
    ID: 9
    Min_Position_Limit: 0
    Max_Position_Limit: 3350
  TC_joint_3:
    ID: 10
    Min_Position_Limit: 1140
    Max_Position_Limit: 2980
  CF_joint_3:
    ID: 11
    Min_Position_Limit: 80
    Max_Position_Limit: 3260
  FT_joint_3:
    ID: 12
    Min_Position_Limit: 0
    Max_Position_Limit: 3350
  TC_joint_4:
    ID: 13
    Min_Position_Limit: 1140
    Max_Position_Limit: 2980
  CF_joint_4:
    ID: 14
    Min_Position_Limit: 80
    Max_Position_Limit: 3260
  FT_joint_4:
    ID: 15
    Min_Position_Limit: 0
    Max_Position_Limit: 3350
  TC_joint_5:
    ID: 16
    Min_Position_Limit: 1140
    Max_Position_Limit: 2980
  CF_joint_5:
    ID: 17
    Min_Position_Limit: 80
    Max_Position_Limit: 3260
  FT_joint_5:
    ID: 18
    Min_Position_Limit: 0
    Max_Position_Limit: 3350