common:
  LED: 1
  Return_Delay_Time: 0
  Drive_Mode: 0
  Operating_Mode: 3
  Acceleration_Limit: 0
  Velocity_Limit: 0
  Profile_Velocity: 0
  Profile_Acceleration: 0
joints:
  # Right

  coxa_joint_0: # Front-right
    ID: 1
    Min_Position_Limit: 1210 # Backward
    Max_Position_Limit: 2960 # Forward
  femur_joint_0:
    ID: 2
    Min_Position_Limit: 860 # Over
    Max_Position_Limit: 3980 # Under
  tibia_joint_0:
    ID: 3
    Min_Position_Limit: 760 # Close
    Max_Position_Limit: 4095 # Extended

  coxa_joint_1:
    ID: 4
    Min_Position_Limit: 1210
    Max_Position_Limit: 2960
  femur_joint_1:
    ID: 5
    Min_Position_Limit: 860
    Max_Position_Limit: 3980
  tibia_joint_1:
    ID: 6
    Min_Position_Limit: 760
    Max_Position_Limit: 4095

  coxa_joint_2:
    ID: 7
    Min_Position_Limit: 1210
    Max_Position_Limit: 2960
  femur_joint_2:
    ID: 8
    Min_Position_Limit: 860
    Max_Position_Limit: 3980
  tibia_joint_2:
    ID: 9
    Min_Position_Limit: 760
    Max_Position_Limit: 4095

  # Left

  coxa_joint_3:
    ID: 10
    Min_Position_Limit: 1140 # Forward
    Max_Position_Limit: 2880 # Backwards
  femur_joint_3:
    ID: 11
    Min_Position_Limit: 80 # Under
    Max_Position_Limit: 3250 # Over
  tibia_joint_3:
    ID: 12
    Min_Position_Limit: 0 # Extended
    Max_Position_Limit: 3350 # Close

  coxa_joint_4:
    ID: 13
    Min_Position_Limit: 1140
    Max_Position_Limit: 2880
  femur_joint_4:
    ID: 14
    Min_Position_Limit: 80
    Max_Position_Limit: 3250
  tibia_joint_4:
    ID: 15
    Min_Position_Limit: 0
    Max_Position_Limit: 3350

  coxa_joint_5:
    ID: 16
    Min_Position_Limit: 1140
    Max_Position_Limit: 2880
  femur_joint_5:
    ID: 17
    Min_Position_Limit: 80
    Max_Position_Limit: 3250
  tibia_joint_5:
    ID: 18
    Min_Position_Limit: 0
    Max_Position_Limit: 3350