mildred:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 1000

  joint_position_controller:
    type: position_controllers/JointGroupPositionController
    joints:
      - TC_joint_0
      - CF_joint_0
      - FT_joint_0
      - TC_joint_1
      - CF_joint_1
      - FT_joint_1
      - TC_joint_2
      - CF_joint_2
      - FT_joint_2
      - TC_joint_3
      - CF_joint_3
      - FT_joint_3
      - TC_joint_4
      - CF_joint_4
      - FT_joint_4
      - TC_joint_5
      - CF_joint_5
      - FT_joint_5

  gazebo_ros_control:
    pid_gains:
      TC_joint_0: {p: 640.0, i: 0.0, d: 4000.0}
      CF_joint_0: {p: 640.0, i: 0.0, d: 4000.0}
      FT_joint_0: {p: 640.0, i: 0.0, d: 4000.0}
      TC_joint_1: {p: 640.0, i: 0.0, d: 4000.0}
      CF_joint_1: {p: 640.0, i: 0.0, d: 4000.0}
      FT_joint_1: {p: 640.0, i: 0.0, d: 4000.0}
      TC_joint_2: {p: 640.0, i: 0.0, d: 4000.0}
      CF_joint_2: {p: 640.0, i: 0.0, d: 4000.0}
      FT_joint_2: {p: 640.0, i: 0.0, d: 4000.0}
      TC_joint_3: {p: 640.0, i: 0.0, d: 4000.0}
      CF_joint_3: {p: 640.0, i: 0.0, d: 4000.0}
      FT_joint_3: {p: 640.0, i: 0.0, d: 4000.0}
      TC_joint_4: {p: 640.0, i: 0.0, d: 4000.0}
      CF_joint_4: {p: 640.0, i: 0.0, d: 4000.0}
      FT_joint_4: {p: 640.0, i: 0.0, d: 4000.0}
      TC_joint_5: {p: 640.0, i: 0.0, d: 4000.0}
      CF_joint_5: {p: 640.0, i: 0.0, d: 4000.0}
      FT_joint_5: {p: 640.0, i: 0.0, d: 4000.0}

#  joint_position_controller:
#    type: effort_controllers/JointGroupPositionController
#    joints:
#      - TC_joint_0
#      - CF_joint_0
#      - FT_joint_0
#      - TC_joint_1
#      - CF_joint_1
#      - FT_joint_1
#      - TC_joint_2
#      - CF_joint_2
#      - FT_joint_2
#      - TC_joint_3
#      - CF_joint_3
#      - FT_joint_3
#      - TC_joint_4
#      - CF_joint_4
#      - FT_joint_4
#      - TC_joint_5
#      - CF_joint_5
#      - FT_joint_5
#    TC_joint_0:
#      pid: {p: 100.0, i: 0.01, d: 10.0}
#    CF_joint_0:
#      pid: {p: 100.0, i: 0.01, d: 10.0}
#    FT_joint_0:
#      pid: {p: 100.0, i: 0.01, d: 10.0}
#    TC_joint_1:
#      pid: {p: 100.0, i: 0.01, d: 10.0}
#    CF_joint_1:
#      pid: {p: 100.0, i: 0.01, d: 10.0}
#    FT_joint_1:
#      pid: {p: 100.0, i: 0.01, d: 10.0}
#    TC_joint_2:
#      pid: {p: 100.0, i: 0.01, d: 10.0}
#    CF_joint_2:
#      pid: {p: 100.0, i: 0.01, d: 10.0}
#    FT_joint_2:
#      pid: {p: 100.0, i: 0.01, d: 10.0}
#    TC_joint_3:
#      pid: {p: 100.0, i: 0.01, d: 10.0}
#    CF_joint_3:
#      pid: {p: 100.0, i: 0.01, d: 10.0}
#    FT_joint_3:
#      pid: {p: 100.0, i: 0.01, d: 10.0}
#    TC_joint_4:
#      pid: {p: 100.0, i: 0.01, d: 10.0}
#    CF_joint_4:
#      pid: {p: 100.0, i: 0.01, d: 10.0}
#    FT_joint_4:
#      pid: {p: 100.0, i: 0.01, d: 10.0}
#    TC_joint_5:
#      pid: {p: 100.0, i: 0.01, d: 10.0}
#    CF_joint_5:
#      pid: {p: 100.0, i: 0.01, d: 10.0}
#    FT_joint_5:
#      pid: {p: 100.0, i: 0.01, d: 10.0}