mildred:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100

#  joint_position_controller:
#    type: effort_controllers/JointGroupPositionController
#    joints:
#      - coxa_joint_0
#      - femur_joint_0
#      - tibia_joint_0
#      - coxa_joint_1
#      - femur_joint_1
#      - tibia_joint_1
#      - coxa_joint_2
#      - femur_joint_2
#      - tibia_joint_2
#      - coxa_joint_3
#      - femur_joint_3
#      - tibia_joint_3
#      - coxa_joint_4
#      - femur_joint_4
#      - tibia_joint_4
#      - coxa_joint_5
#      - femur_joint_5
#      - tibia_joint_5
#
#  gazebo_ros_control:
#    pid_gains:
##      coxa_joint_0: {p: 640.0, i: 0.0, d: 4000.0}
##      femur_joint_0: {p: 640.0, i: 0.0, d: 4000.0}
##      tibia_joint_0: {p: 640.0, i: 0.0, d: 4000.0}
##      coxa_joint_1: {p: 640.0, i: 0.0, d: 4000.0}
##      femur_joint_1: {p: 640.0, i: 0.0, d: 4000.0}
##      tibia_joint_1: {p: 640.0, i: 0.0, d: 4000.0}
##      coxa_joint_2: {p: 640.0, i: 0.0, d: 4000.0}
##      femur_joint_2: {p: 640.0, i: 0.0, d: 4000.0}
##      tibia_joint_2: {p: 640.0, i: 0.0, d: 4000.0}
##      coxa_joint_3: {p: 640.0, i: 0.0, d: 4000.0}
##      femur_joint_3: {p: 640.0, i: 0.0, d: 4000.0}
##      tibia_joint_3: {p: 640.0, i: 0.0, d: 4000.0}
##      coxa_joint_4: {p: 640.0, i: 0.0, d: 4000.0}
##      femur_joint_4: {p: 640.0, i: 0.0, d: 4000.0}
##      tibia_joint_4: {p: 640.0, i: 0.0, d: 4000.0}
##      coxa_joint_5: {p: 640.0, i: 0.0, d: 4000.0}
##      femur_joint_5: {p: 640.0, i: 0.0, d: 4000.0}
##      tibia_joint_5: {p: 640.0, i: 0.0, d: 4000.0}
#
#      coxa_joint_0: {p: 100.0, i: 0.01, d: 10.0}
#      femur_joint_0: {p: 100.0, i: 0.01, d: 10.0}
#      tibia_joint_0: {p: 100.0, i: 0.01, d: 10.0}
#      coxa_joint_1: {p: 100.0, i: 0.01, d: 10.0}
#      femur_joint_1: {p: 100.0, i: 0.01, d: 10.0}
#      tibia_joint_1: {p: 100.0, i: 0.01, d: 10.0}
#      coxa_joint_2: {p: 100.0, i: 0.01, d: 10.0}
#      femur_joint_2: {p: 100.0, i: 0.01, d: 10.0}
#      tibia_joint_2: {p: 100.0, i: 0.01, d: 10.0}
#      coxa_joint_3: {p: 100.0, i: 0.01, d: 10.0}
#      femur_joint_3: {p: 100.0, i: 0.01, d: 10.0}
#      tibia_joint_3: {p: 100.0, i: 0.01, d: 10.0}
#      coxa_joint_4: {p: 100.0, i: 0.01, d: 10.0}
#      femur_joint_4: {p: 100.0, i: 0.01, d: 10.0}
#      tibia_joint_4: {p: 100.0, i: 0.01, d: 10.0}
#      coxa_joint_5: {p: 100.0, i: 0.01, d: 10.0}
#      femur_joint_5: {p: 100.0, i: 0.01, d: 10.0}
#      tibia_joint_5: {p: 100.0, i: 0.01, d: 10.0}

  joint_position_controller:
    type: effort_controllers/JointGroupPositionController
    joints:
      - coxa_joint_0
      - femur_joint_0
      - tibia_joint_0
      - coxa_joint_1
      - femur_joint_1
      - tibia_joint_1
      - coxa_joint_2
      - femur_joint_2
      - tibia_joint_2
      - coxa_joint_3
      - femur_joint_3
      - tibia_joint_3
      - coxa_joint_4
      - femur_joint_4
      - tibia_joint_4
      - coxa_joint_5
      - femur_joint_5
      - tibia_joint_5
    coxa_joint_0:
      pid: {p: 100.0, i: 0.01, d: 10.0}
    femur_joint_0:
      pid: {p: 100.0, i: 0.01, d: 10.0}
    tibia_joint_0:
      pid: {p: 100.0, i: 0.01, d: 10.0}
    coxa_joint_1:
      pid: {p: 100.0, i: 0.01, d: 10.0}
    femur_joint_1:
      pid: {p: 100.0, i: 0.01, d: 10.0}
    tibia_joint_1:
      pid: {p: 100.0, i: 0.01, d: 10.0}
    coxa_joint_2:
      pid: {p: 100.0, i: 0.01, d: 10.0}
    femur_joint_2:
      pid: {p: 100.0, i: 0.01, d: 10.0}
    tibia_joint_2:
      pid: {p: 100.0, i: 0.01, d: 10.0}
    coxa_joint_3:
      pid: {p: 100.0, i: 0.01, d: 10.0}
    femur_joint_3:
      pid: {p: 100.0, i: 0.01, d: 10.0}
    tibia_joint_3:
      pid: {p: 100.0, i: 0.01, d: 10.0}
    coxa_joint_4:
      pid: {p: 100.0, i: 0.01, d: 10.0}
    femur_joint_4:
      pid: {p: 100.0, i: 0.01, d: 10.0}
    tibia_joint_4:
      pid: {p: 100.0, i: 0.01, d: 10.0}
    coxa_joint_5:
      pid: {p: 100.0, i: 0.01, d: 10.0}
    femur_joint_5:
      pid: {p: 100.0, i: 0.01, d: 10.0}
    tibia_joint_5:
      pid: {p: 100.0, i: 0.01, d: 10.0}