<?xml version="1.0"?>
<robot name="mildred"
       xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
       xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
       xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
       xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="$(find mildred_description)/urdf/variables.xacro" />
    <xacro:include filename="$(find mildred_description)/urdf/macros.xacro" />

    <link name="base_link"/>
    <joint name="base_to_thorax" type="fixed">
        <parent link="base_link"/>
        <child link="thorax"/>
        <origin xyz="0.00 0.00 0.00" rpy="0.00 0.00 0.00"/>
    </joint>

    <link name="thorax">
        <visual>
            <origin xyz="0.00 0.00 0.00" rpy="0.00 0.00 0.00"/>
            <geometry>
                <cylinder radius="${thorax_radius}" length="${thorax_height}"/>
            </geometry>
            <material name="yellow">
                <color rgba="255 255 0 1"/>
            </material>
        </visual>
        <collision>
            <origin xyz="0.00 0.00 0.00" rpy="0.00 0.00 0.00"/>
            <geometry>
                <cylinder radius="${thorax_radius}" length="${thorax_height}"/>
            </geometry>
        </collision>
        <xacro:default_inertial/>
        <!--<xacro:default_inertial mass="${thorax_mass}"/>-->
    </link>
    <gazebo reference="thorax">
        <material>Gazebo/Yellow</material>
    </gazebo>

    <!-- Leg Macro -->
    <xacro:macro name="leg" params="suffix angle x y mirror">

        <!-- Link 1/Coxa -->
        <joint name="TC_joint_${suffix}" type="revolute">
            <parent link="thorax"/>
            <child link="coxa_${suffix}"/>
            <origin xyz="${x} ${y} 0.00" rpy="0.00 0.00 ${angle}"/>
            <axis xyz="0.00 0.00 1.00"/>
            <limit lower="${TC_joint_lower_limit}" upper="${TC_joint_upper_limit}" effort="${max_torque}" velocity="${max_velocity}"/>
            <!--<dynamics damping="${damping}" friction="${friction}" />-->
        </joint>
        <link name="coxa_${suffix}">
            <visual>
                <origin xyz="${coxa_length/2} 0.00 0.00" rpy="0.00 ${radians(90)} 0.00"/>
                <geometry>
                    <cylinder radius="0.02" length="${coxa_length}"/>
                </geometry>
                <material name="blue">
                    <color rgba="0 0 255 1"/>
                </material>
            </visual>
            <collision>
                <origin xyz="${coxa_length/2} 0.00 0.00" rpy="0.00 ${radians(90)} 0.00"/>
                <geometry>
                    <cylinder radius="0.02" length="${coxa_length}"/>
                </geometry>
            </collision>
            <xacro:default_inertial/>
            <!--<xacro:cylinder_inertial_with_origin mass="${coxa_mass}" radius="0.02" length="${coxa_length}">-->
                <!--<origin xyz="${coxa_length/2} 0.00 0.00" rpy="0.00 ${radians(90)} 0.00"/>-->
            <!--</xacro:cylinder_inertial_with_origin>-->
        </link>
        <gazebo reference="coxa_${suffix}">
            <material>Gazebo/Blue</material>
        </gazebo>
        <transmission name="TC_trans_${suffix}">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="TC_joint_${suffix}">
                <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            </joint>
            <actuator name="TC_motor_${suffix}">
                <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>

        <!-- Link 2/Femur -->
        <joint name="CF_joint_${suffix}" type="revolute">
            <parent link="coxa_${suffix}"/>
            <child link="femur_${suffix}"/>
            <origin xyz="${coxa_length} 0.00 0.00" rpy="0.00 0.00 0.00"/>
            <axis xyz="0.00 1.00 0.00"/>
            <limit lower="${CF_joint_lower_limit}" upper="${CF_joint_upper_limit}" effort="${max_torque}" velocity="${max_velocity}"/>
            <!--<dynamics damping="${damping}" friction="${friction}" />-->
        </joint>
        <link name="femur_${suffix}">
            <visual>
                <origin xyz="${femur_length/2} 0.00 0.00" rpy="0.00 ${radians(90)} 0.00"/>
                <geometry>
                    <cylinder radius="0.02" length="${femur_length}"/>
                </geometry>
                <material name="blue">
                    <color rgba="0 127 127 1"/>
                </material>
            </visual>
            <collision>
                <origin xyz="${femur_length/2} 0.00 0.00" rpy="0.00 ${radians(90)} 0.00"/>
                <geometry>
                    <cylinder radius="0.02" length="${femur_length}"/>
                </geometry>
            </collision>
            <xacro:default_inertial/>
            <!--<xacro:cylinder_inertial_with_origin mass="${femur_mass}" radius="0.02" length="${femur_length}">-->
                <!--<origin xyz="${femur_length/2} 0.00 0.00" rpy="0.00 ${radians(90)} 0.00"/>-->
            <!--</xacro:cylinder_inertial_with_origin>-->
        </link>
        <gazebo reference="femur_${suffix}">
            <material>Gazebo/Turquoise</material>
        </gazebo>
        <transmission name="CF_trans_${suffix}">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="CF_joint_${suffix}">
                <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            </joint>
            <actuator name="CF_motor_${suffix}">
                <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>

        <!-- Link 3/Tibia -->
        <joint name="FT_joint_${suffix}" type="revolute">
            <parent link="femur_${suffix}"/>
            <child link="tibia_${suffix}"/>
            <origin xyz="${femur_length} 0.00 0.00" rpy="0.00 0.00 0.00"/>
            <axis xyz="0.00 1.00 0.00"/>
            <limit lower="${FT_joint_lower_limit}" upper="${FT_joint_upper_limit}" effort="${max_torque}" velocity="${max_velocity}"/>
            <!--<dynamics damping="${damping}" friction="${friction}" />-->
        </joint>
        <link name="tibia_${suffix}">
            <visual>
                <origin xyz="${tibia_length/2} 0.000 0.00" rpy="0.00 ${radians(90)} 0.00"/>
                <geometry>
                    <cylinder radius="0.02" length="${tibia_length}"/>
                </geometry>
                <material name="blue">
                    <color rgba="0 0 255 1"/>
                </material>
            </visual>
            <collision>
                <origin xyz="${tibia_length/2} 0.000 0.00" rpy="0.00 ${radians(90)} 0.00"/>
                <geometry>
                    <cylinder radius="0.02" length="${tibia_length}"/>
                </geometry>
            </collision>
            <xacro:default_inertial/>
            <!--<xacro:cylinder_inertial_with_origin mass="${tibia_mass}" radius="0.02" length="${tibia_length}">-->
                <!--<origin xyz="${tibia_length/2} 0.00 0.00" rpy="0.00 ${radians(90)} 0.00"/>-->
            <!--</xacro:cylinder_inertial_with_origin>-->
        </link>
        <gazebo reference="tibia_${suffix}">
            <material>Gazebo/Purple</material>
        </gazebo>
        <transmission name="FT_trans_${suffix}">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="FT_joint_${suffix}">
                <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            </joint>
            <actuator name="FT_motor_${suffix}">
                <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>

        <!-- Tip/Foot -->
        <joint name="foot_joint_${suffix}" type="fixed">
            <parent link="tibia_${suffix}"/>
            <child link="foot_frame_${suffix}"/>
            <origin xyz="${tibia_length} 0.00 0.00" rpy="0.00 0.00 0.00"/>
        </joint>
        <link name="foot_frame_${suffix}">
            <visual>
                <origin xyz="0 0 0"/>
                <geometry>
                    <sphere radius="${foot_radius}"/>
                </geometry>
                <material name="red">
                    <color rgba="255 0 0 1"/>
                </material>
            </visual>
            <collision name="foot_collision">
                <origin xyz="0 0 0"/>
                <geometry>
                    <sphere radius="${foot_radius}"/>
                </geometry>
            </collision>
            <xacro:default_inertial/>
            <!--<xacro:sphere_inertial mass="${foot_mass}" radius="0.01"/>-->
        </link>
        <gazebo reference="foot_frame_${suffix}">
            <material>Gazebo/Red</material>
            <!--<mu1 value="1.0"/>-->
            <!--<mu2 value="1.0"/>-->
            <!--<kp value="10000000.0"/>-->
            <!--<kd value="1.0"/>-->
            <!--<fdir1 value="1 0 0"/>-->
        </gazebo>

    </xacro:macro>

    <xacro:leg suffix="0" x="${corner_x}" y="${corner_y}" angle="${radians(leg_angle)}" mirror="-1"/>
    <xacro:leg suffix="1" x="${center_x}" y="0.00" angle="${radians(0)}" mirror="-1"/>
    <xacro:leg suffix="2" x="${corner_x}" y="-${corner_y}" angle="${radians(-leg_angle)}" mirror="-1"/>

    <xacro:leg suffix="3" x="-${corner_x}" y="-${corner_y}" angle="${radians(180 + leg_angle)}" mirror="1"/>
    <xacro:leg suffix="4" x="-${center_x}" y="0.00" angle="${radians(180)}" mirror="1"/>
    <xacro:leg suffix="5" x="-${corner_x}" y="${corner_y}" angle="${radians(180 - leg_angle)}" mirror="1"/>

    <gazebo>
        <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
            <robotNamespace>/mildred</robotNamespace>
        </plugin>
    </gazebo>

</robot>